# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'WeatherBeacon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherBeacon
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'MKBeaconXProSDK'
  target 'WeatherBeaconTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherBeaconUITests' do
    # Pods for testing
  end

end
